package com.hastashilpa.app.util
import android.content.Context
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Environment
import com.hastashilpa.app.data.BatchEntity
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * PdfExporter — creates downloadable PDFs for blueprints and batch reports.
 * Both functions write to the public Downloads folder and return the File,
 * or null on failure (so the caller can show an appropriate Toast).
 *
 * NO CHANGES to exportBlueprint() — it is identical to the original.
 * exportBatchReport() now accepts List<BatchEntity> (Room entities) directly.
 */
object PdfExporter {

    // ─────────────────────────────────────────────────────────────────────
    // 1. BLUEPRINT PDF  (unchanged from original)
    // ─────────────────────────────────────────────────────────────────────

    fun exportBlueprint(
        context: Context,
        name: String,
        dims: String,
        material: String,
        steps: List<String>
    ): File? {
        return try {
            val document = PdfDocument()
            val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
            val page     = document.startPage(pageInfo)
            val canvas   = page.canvas

            val titlePaint = Paint().apply {
                textSize  = 22f
                isFakeBoldText = true
                color     = android.graphics.Color.parseColor("#2E7D32")
            }
            val labelPaint = Paint().apply {
                textSize = 13f
                isFakeBoldText = true
                color    = android.graphics.Color.parseColor("#424242")
            }
            val bodyPaint = Paint().apply {
                textSize = 12f
                color    = android.graphics.Color.parseColor("#616161")
            }
            val dividerPaint = Paint().apply {
                color       = android.graphics.Color.parseColor("#EEEEEE")
                strokeWidth = 1f
            }

            var y = 60f

            // Header bar
            val headerBg = Paint().apply { color = android.graphics.Color.parseColor("#E8F5E9") }
            canvas.drawRect(30f, 30f, 565f, 80f, headerBg)
            canvas.drawText("📐 Hasta-Shilpa Blueprint", 40f, 62f, titlePaint)

            y = 100f
            canvas.drawText(name, 40f, y, titlePaint.apply { textSize = 18f })
            y += 24f
            canvas.drawText("Dimensions : $dims", 40f, y, labelPaint)
            y += 20f
            canvas.drawText("Material   : $material", 40f, y, labelPaint)
            y += 16f
            canvas.drawLine(40f, y, 555f, y, dividerPaint)
            y += 20f

            canvas.drawText("CONSTRUCTION STEPS", 40f, y, labelPaint.apply {
                color = android.graphics.Color.parseColor("#2E7D32")
                textSize = 11f
                letterSpacing = 0.08f
            })
            y += 20f

            steps.forEachIndexed { i, step ->
                val stepLabel = Paint().apply {
                    textSize = 12f
                    isFakeBoldText = true
                    color    = android.graphics.Color.parseColor("#E65100")
                }
                canvas.drawText("Step ${i + 1}", 40f, y, stepLabel)
                y += 16f

                // Wrap long step text
                val words    = step.split(" ")
                var line     = ""
                val maxWidth = 500f
                words.forEach { word ->
                    val test = if (line.isEmpty()) word else "$line $word"
                    if (bodyPaint.measureText(test) < maxWidth) {
                        line = test
                    } else {
                        canvas.drawText(line, 50f, y, bodyPaint)
                        y   += 16f
                        line = word
                    }
                }
                if (line.isNotEmpty()) {
                    canvas.drawText(line, 50f, y, bodyPaint)
                    y += 16f
                }
                y += 8f
            }

            // Footer
            val footerPaint = Paint().apply {
                textSize = 9f
                color    = android.graphics.Color.parseColor("#9E9E9E")
            }
            val dateStr = SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date())
            canvas.drawText("Generated by Hasta-Shilpa · $dateStr", 40f, 820f, footerPaint)

            document.finishPage(page)

            val fileName = "Blueprint_${name.replace(" ", "_")}_$dateStr.pdf"
            val file     = getOutputFile(fileName)
            document.writeTo(FileOutputStream(file))
            document.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // 2. BATCH REPORT PDF  — accepts Room BatchEntity list directly
    // ─────────────────────────────────────────────────────────────────────

    fun exportBatchReport(
        context: Context,
        batches: List<BatchEntity>
    ): File? {
        if (batches.isEmpty()) return null

        return try {
            val document = PdfDocument()
            val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
            val page     = document.startPage(pageInfo)
            val canvas   = page.canvas

            // ── Paints ────────────────────────────────────────────────────
            val titlePaint = Paint().apply {
                textSize       = 20f
                isFakeBoldText = true
                color          = android.graphics.Color.parseColor("#2E7D32")
            }
            val headerPaint = Paint().apply {
                textSize       = 11f
                isFakeBoldText = true
                color          = android.graphics.Color.parseColor("#424242")
                letterSpacing  = 0.06f
            }
            val bodyPaint = Paint().apply {
                textSize = 11f
                color    = android.graphics.Color.parseColor("#616161")
            }
            val boldBodyPaint = Paint().apply {
                textSize       = 11f
                isFakeBoldText = true
                color          = android.graphics.Color.parseColor("#1A1A1A")
            }
            val accentPaint = Paint().apply {
                textSize       = 12f
                isFakeBoldText = true
                color          = android.graphics.Color.parseColor("#2E7D32")
            }
            val dividerPaint = Paint().apply {
                color       = android.graphics.Color.parseColor("#EEEEEE")
                strokeWidth = 1f
            }
            val footerPaint = Paint().apply {
                textSize = 9f
                color    = android.graphics.Color.parseColor("#9E9E9E")
            }

            // ── Page header ───────────────────────────────────────────────
            val headerBg = Paint().apply { color = android.graphics.Color.parseColor("#E8F5E9") }
            canvas.drawRect(30f, 30f, 565f, 80f, headerBg)
            canvas.drawText("🪵 Hasta-Shilpa — Batch Report", 40f, 62f, titlePaint)

            var y = 100f

            // ── Date + summary ────────────────────────────────────────────
            val dateStr     = SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date())
            val totalPoles  = batches.sumOf { it.poles }
            val totalStrips = batches.sumOf { it.strips }

            canvas.drawText("Generated : $dateStr", 40f, y, bodyPaint)
            y += 18f
            canvas.drawText("Total batches : ${batches.size}", 40f, y, bodyPaint)
            y += 18f
            canvas.drawText(
                "Total materials : $totalPoles bamboo poles · $totalStrips cane strips",
                40f, y, bodyPaint
            )
            y += 16f
            canvas.drawLine(40f, y, 555f, y, dividerPaint)
            y += 20f

            // ── Column header row ─────────────────────────────────────────
            val col1 = 40f
            val col2 = 240f
            val col3 = 360f
            val col4 = 460f

            canvas.drawText("PRODUCT",       col1, y, headerPaint)
            canvas.drawText("DATE",          col2, y, headerPaint)
            canvas.drawText("POLES",         col3, y, headerPaint)
            canvas.drawText("STRIPS",        col4, y, headerPaint)
            y += 6f
            canvas.drawLine(40f, y, 555f, y, dividerPaint)
            y += 16f

            // ── Batch rows ────────────────────────────────────────────────
            batches.forEach { batch ->
                // Truncate long product names to fit col width
                val productLabel = if (batch.product.length > 22)
                    batch.product.take(20) + "…" else batch.product

                canvas.drawText(productLabel,        col1, y, boldBodyPaint)
                canvas.drawText(batch.date,          col2, y, bodyPaint)
                canvas.drawText(batch.poles.toString(), col3, y, bodyPaint)
                canvas.drawText(batch.strips.toString(), col4, y, bodyPaint)
                y += 20f

                // Add a new page if we're near the bottom
                if (y > 780f) {
                    document.finishPage(page)
                    val newPage = document.startPage(
                        PdfDocument.PageInfo.Builder(595, 842, document.pages.size + 1).create()
                    )
                    // NOTE: for multi-page support beyond prototype scope,
                    // refactor to a page-state machine. For v1 this is sufficient.
                    y = 60f
                }
            }

            // ── Totals footer row ─────────────────────────────────────────
            y += 4f
            canvas.drawLine(40f, y, 555f, y, dividerPaint)
            y += 18f
            canvas.drawText("TOTALS",              col1, y, headerPaint)
            canvas.drawText("",                    col2, y, headerPaint)
            canvas.drawText(totalPoles.toString(), col3, y, accentPaint)
            canvas.drawText(totalStrips.toString(), col4, y, accentPaint)

            // ── Page footer ───────────────────────────────────────────────
            canvas.drawText(
                "Hasta-Shilpa v1.0 · Bamboo & Cane Artisan Empowerment · $dateStr",
                40f, 825f, footerPaint
            )

            document.finishPage(page)

            val fileName = "BatchReport_$dateStr.pdf"
            val file     = getOutputFile(fileName)
            document.writeTo(FileOutputStream(file))
            document.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Utility — resolves Downloads folder path on all supported API levels
    // ─────────────────────────────────────────────────────────────────────

    private fun getOutputFile(fileName: String): File {
        val dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
        if (!dir.exists()) dir.mkdirs()
        return File(dir, fileName)
    }
}